### ISSUE TITLE
\overline{\F_p} vs \overline{\F}_p

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#1]
Here (and in a couple other places):

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L144

I personally prefer the overline to stop on the 𝔽. Matter of taste. Do as you feel.

**Comment by jake-doliskani** [comment]
True, \overline{\F}_p looks prettier. Changed all of them.
