### ISSUE TITLE
Weird sentence

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#10]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L394-L395

You say "is supersingular" and "is ordinary". That's very confusing. It'd be clearer if you said "the algorithm outputs SUPERSINGULAR/ORDINARY".

**Comment by jake-doliskani** [comment]
Changed to:
If ψ_p (a) = 1 then the algorithm outputs “supersingular”, otherwise it outputs “ordinary”.

**Comment by defeo** [comment]
Add the quotes in the next sentence: 

> then the output is "supersingular"

**Comment by jake-doliskani** [comment]
Done.
