### ISSUE TITLE
Switch coordinates?

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#11]
I'm not 100% sure, but I think here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L576

the two points should rather be (P, x_P) and (P, x_P^n), in order to be consistent with the rest.

**Comment by jake-doliskani** [comment]
Yes, good catch!
