### ISSUE TITLE
Is worst case really worst case?

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#15]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L662-L663

you only prove that, if E is supersingular, the algorithm runs in O(log² p) **on average**. That's not really a "worst case". A proof must be given that a suitable r can be found within O(log p) (but doesn't this need GRH?), or the statement must be changed.

**Comment by jake-doliskani** [comment]
Indeed, this needs GRH. I added a theorem about the density, among all primes, of such r. The theorem is known as "Artin's primitive root" conjecture which holds under GRH.

**Comment by defeo** [comment]
I keep disagreeing with your Theorem 1 (and Prop. 11).

For one, you put forth the average complexity given a random curve as input. However, following Sutherland, the interesting measure is the average complexity **given a supersingular curve** as input. Admittedly, that's a matter of choice, but now that Drew has already made a choice, you're more or less obliged to follow it.

But the real problem is another one. You say that the **worst case** complexity under GRH is O(log²p). That would mean that under GRH your algorithm is **deterministic**. It is not! You're using Shoup's variant of the Cantor-Zassenhaus algorithm, which worst case complexity is not polynomial.

So, the correct statement would be that your algorithm has **average** complexity O(log²p) under GRH, given a supersingular curve as input.

**Comment by jake-doliskani** [comment]
Oh, I didn't actually know what you were saying before. Now I got it. How about

Given an elliptic curve $E/\F_q$, there exists a Las Vegas algorithm that can efficiently 
decide whether $E$ is supersingular or ordinary. On input an ordinary curve the algorithm runs in an expected $\tildO(\log p)$ operations in $\F_p$. On input a supersingular curve, under the generalized Riemann hypothesis, the algorithm runs in an expected $\tildO(\log^2 p)$ operations in $\F_p$.

**Comment by defeo** [comment]
That sounds correct

**Comment by defeo** [comment]
I just realised that you cite Sutherland's algorithm as having complexity O~(log³p) **bit** operations. So it seems that your algorithm has no asymptotic advantage.

However the experiments in Table 1 seem to condraddict the theory: Sutherland's algorithm running time grows much faster than yours.

What do you make of it?

**Comment by jake-doliskani** [comment]
Mmm..., I'm not 100% sure. Maybe in the reduction mod z^r - 1 some time is saved. Probbably there is a loglog(p) factor somewhere...
Another possibility is that my implementation has some bug that I haven't caught!

**Comment by jake-doliskani** [comment]
Well, I also have not claimed that my algorithm has asymptotic advantage. To be honest I just liked to publish the idea.

**Comment by defeo** [comment]
Well, the difference looks much more dramatic than a loglog factor.

Your algorithm seems to have quadratic growth, rather than cubic. How does r grow in your experiments?

**Comment by defeo** [comment]
I'm not criticizing your result. But there's an unexplained phenomenon I'd like to understand. And it plays at your advantage!

**Comment by defeo** [comment]
And, anyway, it's your duty to compare your algorithm with the state of the art. You must give a good reason for the reader to go through your paper. Simply saying "I like the idea is not enough".

**Comment by jake-doliskani** [comment]
I know, actually I tried to fined a proper explanation for a while...
In the experiments r is usually a factor < 1 of the number of bits of p.
Maybe if the experiments are ran for much larger r the two runtimes converge.
I can run the experiments for larger r. I need to change my parameter sets though.

**Comment by javad-doliskani** [comment]
do you want me to run the experiments for larger r?

**Comment by defeo** [comment]
I don't think that would make sense, right? r depends on p (and ε and η, but those also depend on p), so you should just take whatever r is best.

I'd just like to see some comments on the discrepancy between the two algorithms. Give your best explanation. Maybe profiling could help understand what are the bottlenecks, and why Drew's algorithm fares so badly.

**Comment by defeo** [comment]
And, of course, stress in the introduction or in the conclusion that your algorithm is better in practice.

**Comment by jake-doliskani** [comment]
Alright, I'm going to do some profiling. 
I'll let you know.

**Comment by jake-doliskani** [comment]
A detailed profiling revealed the following:

1. The implementation of Drew's algorithm is fine as it is.
2. The little secrete behind the runtimes of the new algorithm was a bug in the parameter generation that caused r to grow at a slower rate that it suppose to. After the fix, the new timings  are unfortunatley not very impressive but still acceptable.
3. I have been a "lousy" implementer on this one.

**Comment by jake-doliskani** [comment]
Added 

Note that, ignoring the logarithmic factors, our result does not asymptotically improve on the 
state-of-the-art algorithm \cite{sutherland2012} ...

to the intro, and 

As the timings suggest, complexities of the two algorithms differ only by a constant factor, which confirms the theory ...

to the experiments section.

**Comment by defeo** [comment]
You could stress in the intro that your algorithm would be an asymptotic improvement if Conjecture 12 can be proven. In the end, that's the most interesting part of this paper: the connection between some high flying theorems and conjectures, and a very concrete algorithmic problem.

Aren't you bothered by the fact that Algo 2 spills over two pages?

**Comment by jake-doliskani** [comment]
Good idea.
I am a little bit bothered by the splitting. I should remove the hack in the preamble.
The same hack is applied in the ffisom paper. I am surprised no one complained.

**Comment by defeo** [comment]
In the ffisom paper I wrapped in figure envs all the algorithms that spilled.

**Comment by defeo** [comment]
Last thing, and then I'll stop bothering you. Could you compare your implementations with Sage/PARI point counting, for good measure? From my experiments the cross point should be somewhere around 300 bits.

Once you've done that, you can resubmit, and I'll quickly green light the paper for the editor. Thanks for your patience, this was interesting.

**Comment by jake-doliskani** [comment]
No problem, it never bothered me at all. I wish all reviewers were like you, willing to put enough time and actually improve a manuscript. Should I do both Sage and Pari? Also just point counting or testing the is_supersingular() function? Cremona was saying that they use point counting but the function is_supersingular() also tests for some predefined j-invariants etc.
In the case of point counting I could just use ordinary curve instead of generating supersingular ones. The timings should be same.

I think the spilling problem is still in the github version of the the ffisom paper. The algorithms don't need to be wrapped in a Figure environment. As soon as you remove the Hack they become floats. Do you want me to update the github version?

**Comment by defeo** [comment]
Sage calls pari. Just test point counting, that's the interesting thing. And, yes, you can use a random curve, that shouldn't change anything.

I hadn't noticed that the non-floating behaviour was a hack. I think the ffisom paper is good like that, reverting the hack would probably shuffle paragraphs around and possibly break things . If we have a 3rd review, we'll revert the hack.

**Comment by jake-doliskani** [comment]
Sage looks extremely slow!!!
Could you also run the following test (for the two small primes):

```
def buildExtensionAndCurve(p):
	Fpp.<i> = GF(p^2, modulus = x^2 + 1)
	E = EllipticCurve(Fpp, [Fpp.random_element(), Fpp.random_element()])
	return Fpp, E


def currentTimeMillis():
	return int(round(time.time() * 1000))


def main():
	primes = [4294967311, 18446744073709551667]
	print "Numbits  time"
	for i in range(0, len(primes)):
		Fpp, E = buildExtensionAndCurve(primes[i])
		time = currentTimeMillis()
		E.count_points()
		time = currentTimeMillis() - time
		print ZZ(primes[i]).nbits(), "     ", time

```

**Comment by defeo** [comment]
I forgot that Sage does naive point counting over extension fields. I had only tested prime fields.

You can directly call pari with

```
E._pari_().ellsea()
```

**Comment by jake-doliskani** [comment]
With that I get:

```
Numbits  time(millis)
33       58
65       473
129       8884
257       115632
```
It looks like the cross point is 129. The times definitely suggest O~((log p)^4).

**Comment by defeo** [comment]
Yup, looks fine, I get similar results (my previous estimate of 300 was bad)
