### ISSUE TITLE
Give an explicit formula for η

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#16]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L624-L628

Without a precise definition for η, the reader can not:

- implement the algorithm,
- verify the correctness of the proof.

Please give more details on the proofs of Theorems 7-8, and on the definition of η.

**Comment by jake-doliskani** [comment]
I added a simplified estimate for \eta as a function of \epsilon for explicit parameters and implementation. But do I really need to reiterate the proofs of Theorems 7-8. It is basically a copy and past and I'm a bit reluctant to do that.

**Comment by defeo** [comment]
Well, you say in the paper that the proof must be modified to make it work
for your case (switching the roles of the curve and the projective line).
It's not the reader's job to play the modification for you.

You can leave out the proof of the lemmas, if there are any, pointing to
Voloch's paper for it. But you should not abuse the reader's "diffing
algorithm" by writing an incremental proof.

Anyway your paper is quite short, so I do not understand why you are
reluctant (other than being lazy, which I can totally understand :)

**Comment by jake-doliskani** [comment]
Ok, details are added. I think it is rather self-contained now.

**Comment by defeo** [comment]
Much better!
