### ISSUE TITLE
Computing the Hasse invariant is cheaper than O(M(p))

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#2]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L154

You can do O(p) ops using the formula in Silverman, Chap V, Theorem 4.1.b.

**Comment by jake-doliskani** [comment]
Done:
A slightly better complexity $O(p)$ can be obtained by using the Deuring polynomial $H_p(x)$ \cite[Theorem 4.1.b]{silverman2009arithmetic}.
