### ISSUE TITLE
Complexity of SEA algorithm is trickier than that

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#3]
https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L161

SEA is a Las Vegas algorithm, with average complexity O~(log⁵ p) (if you average over all elliptic curves for a given prime). However, worst case is the same as plain Schoof, so more like O~(log⁶ p). See the Shparlinski-Sutherland series of papers.

**Comment by jake-doliskani** [comment]
I am a little bit confused about the complexity of point counting. Isn't the following true?
Plain Schoof algorithm with fast arithmetic: O~(log^5 p)
SEA with fast arithmetic and some heuristic assumption: O~(log^4 p)

**Comment by defeo** [comment]
Mmm... ​I'm ​confused too. You are right. See the intro here:
https://arxiv.org/pdf/1404.0399.pdf
