### ISSUE TITLE
The Monte Carlo algorithm, as presented, is not self-evident

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#4]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L166-L167

it would be clearer if you wrote E(𝔽_q) ≅(ℤ/(p±1)ℤ)² instead of the weaker statement on #E(𝔽_q).

**Comment by jake-doliskani** [comment]
Done.
