### ISSUE TITLE
You haven't said what the dual of π is

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#6]
Here:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L358

**Comment by jake-doliskani** [comment]
You mean I define what a dual is? or write the dual of \pi explicitly?

**Comment by defeo** [comment]
​Yes, say what the dual is, and/or point to a reference (e.g. Silverman)
