### ISSUE TITLE
Give the definition of ϕ_p and ω_p

### ISSUE THREAD

**Issue by defeo** [javad-doliskani/divpoly_pit#7]
Here, we don't know what ϕ and ω are:

https://github.com/javad-doliskani/divpoly_pit/blob/98734cc4aff5acd423f0d10277c6f9d0162e0eb5/divpoly_pit.tex#L362-L363

That's going to bite you later, in the proof of Prop. 5, where you explicitly use the definition of ϕ_p, thus forcing the reader to open a book on elliptic curves to follow your proof.

**Comment by jake-doliskani** [comment]
Done.

**Comment by defeo** [comment]
Still. In the proof of Prop. 5 you say

> So if P ∈ E satisfies (6) then x_pP = x_πP

with no justification. Unless there's an argument I'm not seeing, this is a consequence of the formula for ϕ_p; this is not at all evident in Prop. 5, especially given that the only definition of ϕ_p is hidden inside the proof of another proposition.

Can you do something to fix this?

**Comment by jake-doliskani** [comment]
OK, you're right. This
"So if P ∈ E satisfies (6) then x_pP = x_πP"
is really compact. I can define the two polynomials \phi_m and \omega_m right after (1), and reference them.

**Comment by jake-doliskani** [comment]
Done.
